version: 2
jobs:
  build:
    docker:
      - image: continuumio/anaconda3:latest
    steps:
      - run: apt-get install make
      - checkout
      - run:
           name: testing notebooks
           command: |
             make all
